services:
  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: streamora-db-gui
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - streamora-backend-network

volumes:
  pgadmin_data:
